force-app/main/default/objects/Chatbot_Link__mdt.object
<CustomObject>
    <fields>
        <fullName>Link_Name__c</fullName>
        <label>Link Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <label>Chatbot Link</label>
    <pluralLabel>Chatbot Links</pluralLabel>
</CustomObject>

force-app/main/default/classes/chatMessagesController.cls
/**
 * Created by JasonMcGrew on 8/12/2020.
 */

public with sharing class chatMessagesController {
    @AuraEnabled(Cacheable=true)
    public static List<Wraper> getAllChatBotLinks() {
        List<Wraper> lstWrap = new List<Wraper>();
            for(Chatbot_Link__mdt mdata : [
                    SELECT Link_Name__c, Link__c
                    FROM Chatbot_Link__mdt
            ]) {
                lstWrap.add(new Wraper(mdata.Link__c, mdata.Link_Name__c));
            }
        return lstWrap;
    }
    public class Wraper {
        @AuraEnabled
        public String link { get; set; }
        @AuraEnabled
        public String title { get; set; }

        public Wraper(String link, String title) {
            this.link = link;
            this.title = title;
        }
    }
}