force-app/main/default/objects/Commission__c.object
<CustomObject>
    <description>Populated by nightly batch from the Organizer Payment records</description>
    <fields>
        <fullName>Commission_Amount__c</fullName>
        <label>Commission Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission_Percent__c</fullName>
        <label>Commission Percent</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Commissionable_Amount__c</fullName>
        <label>Commissionable Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be an Operator</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Operator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QuotaAttributablePercent__c</fullName>
        <label>Quota Attributable Percent</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Quota_Attributable_Amount__c</fullName>
        <label>Quota Attributable Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Commission Nbr</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TestViewCommissionsController.cls
@isTest
public class TestViewCommissionsController
{
/*
    @isTest
    public static void testAllMethods()
    {
        Account account = new Account(Name = 'test');
        insert account;
        Account_Commission_User__c accountCommissionUser = new Account_Commission_User__c(Account__c = account.Id, Commission_Percent__c = 7.5, QuotaAttributablePercent__c = 7.5);
        insert accountCommissionUser;
        Date payDate = Date.newInstance(2013, 11, 6);
        Organizer_Payment__c organizerPayment = new Organizer_Payment__c(Operator__c = account.Id, Commission_Assigned__c = false, Commissionable_Amount__c = 1000, Payment_Date__c = payDate);
        insert organizerPayment;
        Commission__c commission = new Commission__c(User__c = Userinfo.getUserId(), Payment_Date__c = payDate, Operator__c = account.Id, Commission_Amount__c = 100, Quota_Attributable_Amount__c = 100, QuotaAttributablePercent__c = 7.5, Commissionable_Amount__c = 1000);
        insert commission;
        
        ViewCommissionsController viewCommissionsController = new ViewCommissionsController();
        List<SelectOption> selectOptions = viewCommissionsController.YearsOptions;
        viewCommissionsController.SelectedSalesRep = UserInfo.getUserId();
        viewCommissionsController.FYYear = '2013';
        viewCommissionsController.salesRepSelectListChange();
        System.assertEquals(false, viewCommissionsController.DiplayCommissionInOneMonth);
        
        viewCommissionsController.Month = 12;
        viewCommissionsController.diplayCommissionInOneMonth();
        System.assertEquals(true, viewCommissionsController.DiplayCommissionInOneMonth);
    }
    */
}