force-app/main/default/objects/Contractor_Match__c.object
<CustomObject>
    <description>A fuzzy match of an account from Connect that does not have an Avetta Id</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contractor Matches</relationshipLabel>
        <relationshipName>Contractor_Matches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contractor Matches</relationshipLabel>
        <relationshipName>Contractor_Matches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Global_Parent__c</fullName>
        <label>Global Parent</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Match_Type__c</fullName>
        <defaultValue>&apos;Update Account&apos;</defaultValue>
        <label>Match Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Update Account</fullName>
                </value>
                <value>
                    <fullName>Supplier Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SUID__c</fullName>
        <label>SUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>accountRecordTypeId__c</fullName>
        <label>Account Record Type Id</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>accountRecordType__c</fullName>
        <label>accountRecordType</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>address_Line_2__c</fullName>
        <label>address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>country__c</fullName>
        <label>country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>firstName__c</fullName>
        <label>firstName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>lastName__c</fullName>
        <label>lastName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>postalCode__c</fullName>
        <label>postalCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>state</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>street__c</fullName>
        <label>street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>webUrl__c</fullName>
        <label>webUrl</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contractor Match</label>
    <nameField>
        <label>Contractor Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contractor Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c.object
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State/Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/API_CONNECT_ContractorMatchController.cls
/**
 * Created by brett on 4/12/18.
 */

public with sharing class API_CONNECT_ContractorMatchController {

    public class DTOoptions {
        public Integer page;
        public Integer pageSize;
        public String orderBy;

        public Integer getOffset() {
            return this.page * this.pageSize;
        }
    }

    @AuraEnabled
    public static Integer getContractorMatchesCount() {

        Integer results = [
                SELECT COUNT()
                FROM Contractor_Match__c
        ];

        return results;

    }

    @AuraEnabled
    public static Map<String, String> getAccountTypesMap() {


        String contractor = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Contractor').getRecordTypeId();
        string operator = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Operator').getRecordTypeId();

        Map<String, String> results = new Map<String, String>();
        results.put(contractor, 'Contractor');
        results.put(operator, 'Operator');

        return results;

    }

    @AuraEnabled
    public static Contractor_Match__c[] getContractorMatches(String dto) {

        System.debug(dto);

        API_CONNECT_ContractorMatchController.DTOoptions options = (API_CONNECT_ContractorMatchController.DTOoptions) JSON.deserialize(dto, API_CONNECT_ContractorMatchController.DTOoptions.class);


        System.debug(options);
        String query = 'SELECT Id, Name, City__c, Phone_Number__c, webUrl__c, Account__r.Name, Account__c, accountRecordType__c, Match_Type__c, accountRecordTypeId__c, email__c, street__c, address_line_2__c, country__c, postalCode__c, state__c, firstName__c, lastName__c  FROM Contractor_Match__c ORDER BY ' + options.orderBy + ' LIMIT ' + options.pageSize + ' OFFSET ' + options.getOffset();

        System.debug(query);

        Contractor_Match__c[] results = Database.query(query);
        System.debug(results);

        return results;

    }


    @AuraEnabled
    public static Account[] accountSearch(String searchText) {

        String searchsString = '%' + searchText + '%';

        Account[] results = [
                SELECT
                        Name,
                        Id,
                        RecordTypeId,
                        Status__c,
                        IsBillable__c,
                        Billable_Entity__c,
                        BillingCity,
                        BillingCountry,
                        DBA_Name__c,
                        Fax,
                        Global_Parent__c,
                        Organizer_ID__c,
                        Paying_Facilities__c,
                        Phone,
                        BillingPostalCode,
                        Preferred_Language__c,
                        Registration_Date__c,
                        BillingState,
                        BillingAddress,
                        SUID__c,
                        Tax_ID__c,
                        Primary_Contact_Email__c
                FROM
                        Account
                WHERE Organizer_ID__c LIKE :searchsString
                OR Name LIKE :searchsString
                OR Primary_Contact_Email__c LIKE :searchsString
                ORDER BY Name ASC
                LIMIT 100
        ];

        System.debug(results);
        return results;

    }


    @AuraEnabled
    public static Contact[] contactSearch(String searchText) {

        String searchsString = '%' + searchText + '%';

        Contact[] results = [
                SELECT
                        Name,
                        Id,
                        Email
                FROM
                        Contact
                WHERE Email LIKE :searchsString
                OR Name LIKE :searchsString
                LIMIT 100
        ];

        System.debug(results);
        return results;

    }

    @AuraEnabled
    public static Account accountFetch(String searchId) {


        Account results = [
                SELECT
                        Name,
                        Id,
                        RecordTypeId,
                        Status__c,
                        IsBillable__c,
                        Billable_Entity__c,
                        BillingCity,
                        BillingCountry,
                        DBA_Name__c,
                        Fax,
                        Global_Parent__c,
                        Organizer_ID__c,
                        Paying_Facilities__c,
                        Phone,
                        BillingPostalCode,
                        Preferred_Language__c,
                        Registration_Date__c,
                        BillingState,
                        BillingAddress,
                        SUID__c,
                        Tax_ID__c,
                        Primary_Contact_Email__c,
                        Website
                FROM Account
                WHERE Id = :searchId
        ];

        System.debug(results);
        return results;

    }

    @AuraEnabled
    public static Contractor_Match__c clearAccountMatch(String matchId) {

        Contractor_Match__c match = new Contractor_Match__c(Id = matchId, Account__c = null);

        update match;

        return match;


    }

    @AuraEnabled
    public static Contractor_Match__c saveAccountMatch(String matchId, String accountId) {

        Contractor_Match__c match = new Contractor_Match__c(Id = matchId, Account__c = accountId);

        update match;

        return match;
    }

    @AuraEnabled
    public static Contact contactFetch(String searchId) {


        Contact results = [
                SELECT
                        Name,
                        Id,
                        Phone,
                        Email

                FROM Contact
                WHERE Id = :searchId
        ];

        System.debug(results);
        return results;

    }

    @AuraEnabled
    public static Contractor_Match__c clearContactMatch(String matchId) {

        Contractor_Match__c match = new Contractor_Match__c(Id = matchId, Contact__c = null);

        update match;

        return match;


    }

    @AuraEnabled
    public static Contractor_Match__c saveContactMatch(String matchId, String contactId) {

        Contractor_Match__c match = new Contractor_Match__c(Id = matchId, Contact__c = contactId);

        update match;

        return match;
    }

    @AuraEnabled
    public static void approveMatch(String matchId, String accountId) {


        Contractor_Match__c match = API_CONNECT_Helpers.getContractorMatch(matchId);

        Account account = [
                SELECT
                        Id,
                        Organizer_ID__c
                FROM
                        Account
                WHERE
                        Id = :accountId
        ];

        try {
            API_CONNECT_Helpers.updateAccount(account, match);

            delete match;
        } catch (Exception e) {
            API_CONNECT_Helpers.logException(e);
            throw e;
        }
    }

    @AuraEnabled
    public static void deleteMatch(String matchId) {


        Contractor_Match__c match = API_CONNECT_Helpers.getContractorMatch(matchId);

        try {
            delete match;
        } catch (Exception e) {
            API_CONNECT_Helpers.logException(e);
            throw e;
        }
    }

    @AuraEnabled
    public static void createAccountFromMatch(String matchId) {

        Contractor_Match__c match = API_CONNECT_Helpers.getContractorMatch(matchId);

        try {
            match.Account__c = API_CONNECT_Helpers.insertContractorAccount(match).Id;
            API_CONNECT_Helpers.insertContractorContact(match);

            delete match;
        } catch (Exception e) {
            API_CONNECT_Helpers.logException(e);
            throw e;
        }
    }

    @AuraEnabled
    public static void createOpportunityFromMatch(String matchId) {

        Contractor_Match__c match = API_CONNECT_Helpers.getContractorMatch(matchId);

        try {

            if (match.Account__c == null) {
                match.Account__c = API_CONNECT_Helpers.insertContractorAccount(match).Id;
            }

            if (match.Contact__c == null) {
                match.Contact__c = API_CONNECT_Helpers.insertContractorContact(match).Id;
            }

            API_CONNECT_Helpers.insertOpportunityFromMatch(match);

            delete match;
        } catch (Exception e) {
            API_CONNECT_Helpers.logException(e);
            throw e;
        }
    }


}