force-app/main/default/objects/ISR_Quota__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ISR_Quotas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ISR_Quotas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quota__c</fullName>
        <label>Quota</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ISR Quota</label>
    <nameField>
        <label>ISR Quota Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ISR Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestISRQuoteController.cls
@isTest(SeeAllData=true)
public class TestISRQuoteController
{
    @isTest
    static void testDefineISRQuotaController()
    {
        User employee = [select Id, SalesManager__c from User where IsActive = true and id != :UserInfo.getUserId() limit 1];
        employee.SalesManager__c = UserInfo.getUserId();
        update employee;
        ISR_Quota__c quota1 = new ISR_Quota__c(Month__c = Date.today().toStartOfMonth(), Quota__c = 1000, Year__c = String.valueOf(date.today().year()), Employee__c = employee.Id, Manager__c = UserInfo.getUserId());
        insert quota1;
        DefineISRQuoteController controller = new DefineISRQuoteController();
        for(DefineISRQuoteController.ISRQuoteInfo isrQUota : controller.CurrentSalesManagerISRQuotes[0].CurrentQuotes)
        {
            if(isrQUota.ISRQuote.Month__c != Date.today().toStartOfMonth())
            {
                isrQUota.ISRQuote.Quota__c = 100;
            }
        }
        system.assert(controller.AllQuotesMonths != null);
        system.assert(controller.AllSalesOptions != null);
        controller.defineQuotes();
    }
    
    @isTest
    static void testViewISRQuotaController()
    {
        User employee = [select Id, SalesManager__c from User where IsActive = true and id != :UserInfo.getUserId() limit 1];
        employee.SalesManager__c = UserInfo.getUserId();
        update employee;
        ISR_Quota__c quota1 = new ISR_Quota__c(Month__c = Date.today().toStartOfMonth(), Quota__c = 1000, Year__c = String.valueOf(date.today().year()), Employee__c = employee.Id, Manager__c = UserInfo.getUserId());
        insert quota1;
        ISRViewQuotasController controller = new ISRViewQuotasController();
        controller.SelectUserId = UserInfo.getuserId();
        controller.Year = String.valueOf(Date.Today().year());
        controller.populateQuotas();
        system.assert(controller.AllSalesOptions != null);
        system.assert(controller.AllSalesManagerOptions != null);
        system.assert(controller.AllYearsOptions != null);
        system.assert(controller.AllQuotesMonths != null);
    }  
}