force-app/main/default/objects/Operator_Contractor__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of Operator Contractor Connection</description>
        <label>Connection Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disconnected</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Operator Contractor</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Operator Contractor Nbr</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operator  Contractor Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/updateOCStatusFromAccountTest.cls
@isTest(SeeAllData=true) private class updateOCStatusFromAccountTest {
    
    @isTest(SeeAllData=true) static void testOCStatusChange() {
        
        //Create contactor record for test purposes.
        List<Account> contractorRecords = QB_TestDataFactory.createAccountRecords(1, TRUE);
        	System.debug('after creating account in QB_TestDataFactory.createAccountRecords') ;  
        
        //Create operator record for test purposes.
        List<Account> operatorRecords = QB_TestDataFactory.createClientAccountRecords(1, TRUE);
        	System.debug('after creating account in QB_TestDataFactory.createAccountRecords');
        	
        System.debug(contractorRecords[0]);    
        System.debug(operatorRecords[0]);    
        
        //Create operator contractor linked to previously created accounts
        List<Operator_Contractor__c> operatorContractorRecords = QB_TestDataFactory.createOperatorContractorRecords(1, TRUE, operatorRecords[0].id, contractorRecords[0].id);
	
        System.debug('Operator Contractor Created ' + operatorContractorRecords[0]);
        System.debug('****************** Insert Account and Operator Contractor record...');
    
        System.debug('Contractor status before' + contractorRecords[0].Status__c);
        contractorRecords[0].Status__c = 'Demo';
        System.debug('Contractor status after' + contractorRecords[0].Status__c);
        update contractorRecords[0];
        
        System.debug('New OC Status = ' + operatorContractorRecords[0]);
    }
}