force-app/main/default/objects/Staging_Results__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Result_Url__c</fullName>
        <label>Batch Result Url</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Staging Results</relationshipLabel>
        <relationshipName>Staging_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Conversion_Executed_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conversion Executed by</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Staging_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Accounts_Converted__c</fullName>
        <label>Number of Accounts Converted</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Contacts_Converted__c</fullName>
        <label>Number of Contacts Converted</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Opportunities_Converted__c</fullName>
        <label>Number of Opportunities Converted</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Staging Results</label>
    <nameField>
        <label>Staging Results</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c.object
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State/Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Staging__c.object
<CustomObject>
    <description>This is the Supplier Staging table used by the Supplier Import Tool.</description>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Supplier Staging (Account ID)</relationshipLabel>
        <relationshipName>Supplier_StagingAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Additional_information__c</fullName>
        <label>Additional information</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Supplier Stagings</relationshipLabel>
        <relationshipName>Supplier_Stagings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact ID</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Supplier Staging (Contact ID)</relationshipLabel>
        <relationshipName>Supplier_StagingContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Converted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Free_Connection__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this connection would result in payment. True, if this connection will make the supplier stay within the same tier.</description>
        <label>Free Connection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organizer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Organizer ID</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner ID</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Supplier_Staging1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Zip_Code__c</fullName>
        <label>Postal/Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <description>Added per Michelle Matias</description>
        <label>Site</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <label>Tax Id</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_ID__c</fullName>
        <label>Vendor ID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Supplier Staging</label>
    <nameField>
        <label>Supplier Staging  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/QB_BacthConvertSuppliers.cls
global class QB_BacthConvertSuppliers implements Database.Batchable<sObject> {
	
	String soqlQuery;
	public String convertCampaignId;
	
	global QB_BacthConvertSuppliers() {
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		String soqlQuery = ' SELECT Account_ID__c,Additional_information__c,Campaign__c,Converted__c, City__c, ' +
                           ' Company__c,Country__c,Email__c, First_Name__c,IsDeleted,Last_Name__c, '+
                           ' Owner_ID__c, Phone__c, Postal_Zip_Code__c,Priority__c,State__c,Street__c, Free_Connection__c, '+
                           ' Tax_Id__c,Website__c, Contact_ID__c, Organizer_ID__c, Vendor_ID__c, Site__c '+ 
                      	   ' FROM Supplier_Staging__c '+
                      	   ' WHERE Campaign__c = :convertCampaignId AND Converted__c = FALSE';
		
		system.debug ('soqlQuery: ' + soqlQuery);
		return Database.getQueryLocator(soqlQuery);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
   		
   		system.debug ('execute. Number of records: ' + scope.size());
   		List<Supplier_Staging__c> myStagingRecords = (List<Supplier_Staging__c>)scope;
		QB_SupplierConvertService.convertSuppliers (myStagingRecords, convertCampaignId );
		   		system.debug ('Converted one batch: ' + scope.size());
		
	}
	
	global void finish(Database.BatchableContext BC) {

		/*
		 // Update Supplier Staging Results with the amount of records that were created and BatchURL.
            Staging_Results__c res = new Staging_Results__c();   
            res.Number_of_Accounts_Converted__c = 0;
            res.Number_of_Contacts_Converted__c = -1;
            res.Number_of_Opportunities_Converted__c = -1;
            res.Batch_Result_Url__c = '*****Batch Request Completed*****';
            res.Conversion_Executed_by__c = UserInfo.getUserId();
            res.Campaign__c = convertCampaignId; 
            
            insert res; */
		
	}
	
	     
}