force-app/main/default/objects/Utterance_Log__c.object
<CustomObject>
    <description>Tracks Utterances that Confused Bot</description>
    <fields>
        <fullName>Chat_Transcript__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chat Transcript</label>
        <referenceTo>LiveChatTranscript</referenceTo>
        <relationshipLabel>Utterance Logs</relationshipLabel>
        <relationshipName>Utterance_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrentUtterance__c</fullName>
        <label>Current Utterance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deployment_Version__c</fullName>
        <label>Deployment Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Utterance Log</label>
    <nameField>
        <displayFormat>UT-{0000}</displayFormat>
        <label>Utterance Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utterance Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LogUtterance.cls
public with sharing class LogUtterance {

public class LogInput{

    @InvocableVariable(required=false)

    public String sCurrentUtterance;

    @InvocableVariable(required=true)

    public String sLiveAgentTranscriptId;

    @InvocableVariable(required=false)

    public String sDeploymentVersion;

}

 

@InvocableMethod(label='Log Utterance')

public static void logUtterance(List<LogInput> inputParameters)

{

    String sCurrentUtterance = inputParameters[0].sCurrentUtterance;

    String sLiveAgentTranscriptId = inputParameters[0].sLiveAgentTranscriptId;

    String sDeploymentVersion = inputParameters[0].sDeploymentVersion;




 

    // Create a new Utterance Log record

    Utterance_Log__c logRecord = new Utterance_Log__c();

 

    // Store the utterance

    logRecord.CurrentUtterance__c = sCurrentUtterance;

    logRecord.Chat_Transcript__c = sLiveAgentTranscriptId;

    logRecord.Deployment_Version__c = sDeploymentVersion;



 

    // Save the log utterance record to our org

    insert logRecord;

}

}